from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    """Persistence contract used by the runtime. Implementations must store
    approvals and an append-only audit log."""

    def create_approval(self, tool_name: str, tool_args: dict, user_role: str) -> str: ...
    def get_approval(self, approval_id: str) -> dict | None: ...
    def update_approval_status(self, approval_id: str, status: str) -> dict | None: ...
    def list_approvals(self, status: str | None = None, limit: int | None = 100) -> list[dict]: ...
    def log_event(self, event_type: str, payload: dict) -> None: ...
    def list_audit_logs(self, limit: int | None = 50) -> list[dict]: ...
